### ISSUE TITLE
deploy-git: Couldn't find remote ref master

### ISSUE THREAD

**Issue by aleclarson** [reframejs/reframe#50]
```sh
reframe create react-frontend
```
After using https://github.com/new to create a repository:
```sh
reframe build & reframe deploy
```

The `deploy` command logged out:
```sh
Deploying build from a few seconds ago.

 ⠧ Loading master of git@github.com:foo/bar

fatal: Couldn't find remote ref master


~/node_modules/simple-git/src/git.js:1555
            callback(error, null);
            ^
Error: fatal: Couldn't find remote ref master

    at ~/node_modules/simple-git/promise.js:21:26
    at Git.<anonymous> (~/node_modules/simple-git/src/git.js:1555:13)
    at Function.Git.fail (~/node_modules/simple-git/src/git.js:1480:18)
    at fail (~/node_modules/simple-git/src/git.js:1438:20)
    at ~/node_modules/simple-git/src/git.js:1447:16
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

## `reframe version`
```sh

   Cli:
      @reframe/cli@0.3.1

   Plugins:
      @reframe/react-kit@0.3.1
      @reframe/deploy-git@0.3.1

```

**Comment by brillout** [comment]
That's because the repo `github.com:foo/bar` doesn't exist.

You can set your `reframe.config.js` to, for example:
~~~js
module.exports = {
  buildRepository: {
    remote: 'git@github.com:aleclarson/repro',
    branch: 'reframe-dist',
  },
};
~~~

It will then push the bundles to that branch `reframe-dist`. If I remember correctly, GitHub pages can also deploy non-master branches.

**Comment by brillout** [comment]
Any luck with this?

**Comment by brillout** [comment]
Reframe is now a collection of libraries and starters. I didn't re-implement auto-deploy for static websites for the new Reframe version because it's not a top priority anymore.
